import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const getCookie = async () => {
    const response = await fetch('/api/getCookie', {
      method: 'GET',
      credentials: 'include'
    })
    console.log(response.status)
  }
  const testCookie = async () => {
    const response = await fetch('/api/testCookie', {
      method: 'GET'
      // credentials: 'include'
    })
    console.log(response.status)
  }
  const testCookieOnAnotherDomain = async () => {
    const response = await fetch(
      'https://cross-origin-cookie-test.herokuapp.com/test',
      {
        method: 'GET',
        credentials: 'include'
      }
    )
    console.log(response.status)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <button onClick={getCookie}>Get cookie</button>
        <button onClick={testCookie}>Send cookie to same domain</button>
        <button onClick={testCookieOnAnotherDomain}>
          Send cookie to another domain
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
